#18 daily-standup
DevopsChina/openpracticelibrary-cn pull request #44
Opened 2023-05-06 06:40 UTC by HebeChe

commit for ticket：https://github.com/DevopsChina/openpracticelibrary-cn/issues/18

2023-05-06 06:46 UTC, HebeChe commented
some further materials could not be viewed, I removed them from my translated file, such like IBM Daily Standup with YouTube link https://www.youtube.com/watch?v=GzQjGhD5tSU

2023-05-06 06:54 UTC, martinliu commented
> some further materials could not be viewed, I removed them from my translated file, such like IBM Daily Standup with YouTube link https://www.youtube.com/watch?v=GzQjGhD5tSU

I will transfer it to Bilibili and we will add a bilibili shortcode of it.

2023-05-06 07:07 UTC, martinliu requested changes
增加了一些改进建议。
YouTube的视频会稍后发到评论中。

2023-05-06 07:07 UTC, martinliu commented on content/posts/daily-standup/daily-standup.md
> +每日站会是由团队统一节奏的，在固定的时间发生的，帮助团队内部快速同步进展的实践活动
‘由’
这个字会不会多余了一点。

2023-05-06 07:07 UTC, martinliu commented on content/posts/daily-standup/daily-standup.md
> +  - Product Owner
Product Owner  -- > 产品负责人 

术语表请先参考：https://github.com/DevOps-Handbook/DevOps-Handbook.github.io/blob/master/glossary.md

2023-05-06 07:07 UTC, martinliu commented on content/posts/daily-standup/daily-standup.md
> +  * 使用线上可视化的计时器，确保站会时长控制在15min之内。核心会议议程：
15min 翻译成 15 分钟

尽可能翻译成全中文，在必要的地方留下英文（避免歧义）

2023-05-06 07:07 UTC, martinliu commented on content/posts/daily-standup/daily-standup.md
> +- [每日站会提醒音乐播放列表](https://www.youtube.com/playlist?list=PLnqlDDtSH2A7jzZiYPMHy2HjjjdV3rhNM&jct=ykj79fMNekbkUwePDbdsjY2QXKaeag)
我们会把这里的几个YouTube视频搬运到B站，然后在插入回这里。

2023-05-06 07:07 UTC, martinliu commented on content/posts/daily-standup/daily-standup.md
> +- 发布日期：AUGUST 10, 2018
参考下面的示例代码

```
> 原文作者

![](https://github.com/prakritiverma.png)

- Prakriti Koller
- PUBLISHED JUNE 29, 2019

> 原文链接：<https://openpracticelibrary.com/practice/lean-coffee/>
```

在原文链接的页面中尽量找到作者头像。

2023-05-06 07:07 UTC, martinliu requested changes
增加了一些改进建议。
YouTube的视频会稍后发到评论中。

2023-05-06 07:19 UTC, martinliu commented on content/posts/daily-standup/daily-standup.md
> +---
文件名需要修改
 daily-standup.md  --> index.zh-cn.md

2023-05-06 07:37 UTC, HebeChe commented on content/posts/daily-standup/daily-standup.md
> +templateKey: practice-page
Done, without "link", as I do not have personal blog yet.

2023-05-06 07:38 UTC, martinliu commented
视频的短代码如下，加到扩展资源部分。
```
{{< bilibili BV1Jk4y1j7UM >}}

{{< bilibili BV1PP41117ZH >}}
```

2023-05-06 07:38 UTC, HebeChe commented on content/posts/daily-standup/daily-standup.md
> +每日站会是由团队统一节奏的，在固定的时间发生的，帮助团队内部快速同步进展的实践活动
Done.

2023-05-06 07:39 UTC, HebeChe commented on content/posts/daily-standup/daily-standup.md
> +  - Product Owner
Done

2023-05-06 07:40 UTC, HebeChe commented on content/posts/daily-standup/daily-standup.md
> +  * 使用线上可视化的计时器，确保站会时长控制在15min之内。核心会议议程：
Got it and Done.

2023-05-06 07:40 UTC, HebeChe commented on content/posts/daily-standup/daily-standup.md
> +- [每日站会提醒音乐播放列表](https://www.youtube.com/playlist?list=PLnqlDDtSH2A7jzZiYPMHy2HjjjdV3rhNM&jct=ykj79fMNekbkUwePDbdsjY2QXKaeag)
Got it

2023-05-06 08:02 UTC, HebeChe commented on content/posts/daily-standup/daily-standup.md
> +- 发布日期：AUGUST 10, 2018
Done. Only keep 1 author, as there were 5 authers for this practice.  Reader could get them from raw link below.

2023-05-06 08:43 UTC, martinliu commented on content/posts/daily-standup/daily-standup.md
> +templateKey: practice-page
it's ok.

2023-05-10 03:53 UTC, HebeChe commented on content/posts/daily-standup/daily-standup.md
> +---
Done

2023-05-10 05:42 UTC, martinliu approved these changes
LGTM

2023-05-10 05:46 UTC, merged

2023-05-15 09:13 UTC, 8ar10der commented
After review and approve it.