一切皆代码
DevopsChina/openpracticelibrary-cn pull request #65
Opened 2023-08-22 02:35 UTC by actini

2023-08-22 02:37 UTC, actini commented
感觉这篇文章有点水，干货没有其他文章那么干
请帮忙校对 @martinliu @dkleng @PikeLiang @allengaller

2023-08-22 03:32 UTC, martinliu requested changes

2023-08-22 03:32 UTC, martinliu commented on content/posts/everything-as-code/index.zh-cn.md
> +---
这里需要加一个
`<!--more-->`

2023-08-22 03:32 UTC, martinliu commented on content/posts/everything-as-code/index.zh-cn.md
> +- PUBLISHED AUGUST 15, 2018
这一行需要删掉：
- PUBLISHED AUGUST 15, 2018

2023-08-22 03:32 UTC, martinliu commented on content/posts/everything-as-code/index.zh-cn.md
> +- Donal Spring
这两行名字后面，可以加上他们的头像，头像图片的url 在原文上可以看到 https://github.com/springdo.png

2023-09-11 16:35 UTC, actini commented on content/posts/everything-as-code/index.zh-cn.md
> +- PUBLISHED AUGUST 15, 2018
 其他文章都有这个啊，为啥要删掉

2023-09-11 16:36 UTC, actini commented on content/posts/everything-as-code/index.zh-cn.md
> +---
这个不是注释吗？加不加没影响的？

2023-09-11 17:53 UTC, actini commented
@martinliu 已经修改～请再校对一遍吧

2023-10-07 14:30 UTC, merged