Code commit for issue #20
DevopsChina/openpracticelibrary-cn pull request #69
Opened 2023-10-30 06:43 UTC by HebeChe

Code commit for issue #20 Definition of done

2023-11-01 02:43 UTC, martinliu requested changes
有两处修改建议，请查看。

2023-11-01 02:43 UTC, martinliu commented on content/posts/definition-of-done/index.zh-cn.md
> +author:
这里是不是重复了两个 author

2023-11-01 02:43 UTC, martinliu commented on content/posts/definition-of-done/index.zh-cn.md
> +> 原文作者
这里是否可以给原作者加一个头像

2023-11-06 05:41 UTC, HebeChe commented on content/posts/definition-of-done/index.zh-cn.md
> +author:
删除多余的一个author

2023-11-06 05:48 UTC, HebeChe commented on content/posts/definition-of-done/index.zh-cn.md
> +> 原文作者
Yes

2023-11-06 06:27 UTC, merged